---
layout: '[layout]'
copyright: true
title: 编译vim8.2时遇到的错误
date: 2020-04-04 19:02:39
tags: 
    - vim
    - hard
categories: vim
abbrlink: the-errors-when-compeling-vim8.2
---
<!-- toc -->

----
* Error information below:
    ```
    no terminal library found
    checking for tgetent()... configure: error: NOT FOUND!
    You need to install a terminal library; for example ncurses.
    Or specify the name of the library with --with-tlib.
    ```

    解决方法:
    ```
    sudo apt-get install libncurses5-dev libncursesw5-dev
    ```
    It worked on Ubuntu16.04.

* E492: Not an editor command: NERDTreeToggle
     此错误是在我使用`:PlugInstall`后按下`F3`(此处F3是开启目录树)出现的。
     > 你知道这个问题的错误原因是什么吗?
     > 你知道这个问题的错误原因是什么吗?
     > 你知道这个问题的错误原因是什么吗?
     > 说出来你可能不相信，我忘记将`Plug nerdtree...`写进自己的配置文件了。一直
     > 以为是其他的什么问题。原来最大的问题就是自己没有装这个插件!!!

* tarbar不能使用
 前提是安装好ctags

* leaderF
     vim.error: Vim: E117: unknown function: bufadd
     猜测原因: vim版本的原因，现在的是vim7.4，但是那个popup界面是需要vim8的.
     > Not this reason uppon. It's because the compiled vim has no python and 
     > python3 lib.
     > 这个错误在python环境装好之后自动消失了。

* vim不支持'+y'粘贴操作
     Use `:echo has("clipboard")` to check.
     >But now I can use it in Gvim. And +python and +python3 can be used in Gvim
     >too! I have no idea.
     网上的i解决办法: `sudo apt-get install vim-gnome`来安装`gvim`，但是安装了
     之后依旧不能解决.
     **解决方法**:
     在`.bashrc`文件中加入
     ```
     alias vim='gvim -v'
     ```
     然后`$source .bashrc`,再次查看`$vim --version | grep "clipboard"`后发现
     ```
     +clipboard +xterm_clipboard
     ```
     > 这个错误在python环境装好之后自动消失了。

* Error: LeaderF requires vim compiled with +python or +python3
    需要在vimi编译的时候加上`--enable-pythoninterp`, `--with-python-config-dir`
    options.
    > 按照上边的执行设置并未其作用。
    > 使用:echo has("python")和:echo has("python3")没有相应的结果
    下边是另一个设置:(但未尝试)
    ```
    --enable-python3interp=yes
    --with-python3-command=/usr/bin/python3
    --with-python3-config-dir=
    ```
* Error: Error detected while processing function leaderf#Gtags#updateGtags:
line 1: E121: Undefined variable: g:Lf_py
    > 这个错误在python环境装好之后自动消失了。
